### PR TITLE
updated dates

### PR DESCRIPTION
**Pull request by sarthakpati**

### CODE REVIEW

**Review by mzenk — COMMENTED** [review]
This could raise questions with task 2 participants because there are no parameters that they could submit separately. maybe add ... short paper (both tasks) and parameters... (task 1; ..) for the Aug 2nd deadline?

**Comment by sarthakpati** [comment]
How about:

```
| **02 Aug** | Final submission of short paper (both tasks) and parameters (task-1) and weights (task-2) of prediction algorithm (no algorithmic changes permitted). |
```

**Comment by mzenk** [comment]
I would just leave the container submission deadline for task-2 as is (since I haven't received requests to extend it). So this would be my suggestion:

`| **02 Aug** | Final submission of short paper (both tasks) and parameters of prediction algorithm (task-1; no algorithmic changes permitted). |`

What do you think?

**Comment by sarthakpati** [comment]
Done!

**Review by mzenk — APPROVED** [review]

**Pull request merged**
