### PR TITLE
Release code and instructions for container test and submission

### PR DESCRIPTION
**Pull request by mzenk**
This PR includes updates to the readme as well as additional python scripts for testing singularity containers.
The readme now describes how to get access to the container submission platform and how to test containers on sample data locally.

### CODE REVIEW

**Review by dzimmerer — APPROVED** [review]
Looks good 
(only not sure with first come first serve policy and unlimited # submissions...)

**Comment by mzenk** [comment]
The timestamp of the last submission will determine the order of evaluation. Do you think that's a problem? Should I clarify this?

**Review by mzenk — COMMENTED** [review]
minor

**Comment by mzenk** [comment]
@sarthakpati only if you have a minute. I pushed a tiny commit after David's review...

**Review by sarthakpati — APPROVED** [review]
Hey @mzenk, apologies, this somehow slipped through my notifications. Anyway, this LGTM!

**Pull request merged**
